flags:
  text:
    integer-simple: false
extra-package-dbs: []
packages:
- '.'
- https://hackage.haskell.org/package/bson-generic-0.0.8.1/bson-generic-0.0.8.1.tar.gz
extra-deps:
- text-1.2.1.3
resolver: lts-5.18
